/**
 * Service Portal API
 * This is a API to fetch and order catalog items from different cloud sources
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AddPortfolioItem model module.
* @module model/AddPortfolioItem
* @version 1.0.0
*/
export default class AddPortfolioItem {
    /**
    * Constructs a new <code>AddPortfolioItem</code>.
    * @alias module:model/AddPortfolioItem
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AddPortfolioItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddPortfolioItem} obj Optional instance to populate.
    * @return {module:model/AddPortfolioItem} The populated <code>AddPortfolioItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddPortfolioItem();

            
            
            

            if (data.hasOwnProperty('portfolio_item_id')) {
                obj['portfolio_item_id'] = ApiClient.convertToType(data['portfolio_item_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} portfolio_item_id
    */
    portfolio_item_id = undefined;








}


